# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/arty.xdc

# Block Designs: bd/SYSTEM/SYSTEM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM || ORIG_REF_NAME==SYSTEM} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_clk_wiz_0_0 || ORIG_REF_NAME==SYSTEM_clk_wiz_0_0} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_CLK60_0_0/SYSTEM_CLK60_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_CLK60_0_0 || ORIG_REF_NAME==SYSTEM_CLK60_0_0} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_COUNTER_0_0/SYSTEM_COUNTER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_COUNTER_0_0 || ORIG_REF_NAME==SYSTEM_COUNTER_0_0} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_axi_gpio_0_0/SYSTEM_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_axi_gpio_0_0 || ORIG_REF_NAME==SYSTEM_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_mig_7series_0_1/SYSTEM_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_mig_7series_0_1 || ORIG_REF_NAME==SYSTEM_mig_7series_0_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_microblaze_0_1/SYSTEM_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_microblaze_0_1 || ORIG_REF_NAME==SYSTEM_microblaze_0_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_dlmb_v10_1/SYSTEM_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_dlmb_v10_1 || ORIG_REF_NAME==SYSTEM_dlmb_v10_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_ilmb_v10_1/SYSTEM_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_ilmb_v10_1 || ORIG_REF_NAME==SYSTEM_ilmb_v10_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_dlmb_bram_if_cntlr_1/SYSTEM_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==SYSTEM_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_ilmb_bram_if_cntlr_1/SYSTEM_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==SYSTEM_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_lmb_bram_1/SYSTEM_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_lmb_bram_1 || ORIG_REF_NAME==SYSTEM_lmb_bram_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_xbar_1/SYSTEM_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_xbar_1 || ORIG_REF_NAME==SYSTEM_xbar_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_microblaze_0_axi_periph_1/SYSTEM_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_microblaze_0_axi_periph_1 || ORIG_REF_NAME==SYSTEM_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_microblaze_0_axi_intc_1/SYSTEM_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_microblaze_0_axi_intc_1 || ORIG_REF_NAME==SYSTEM_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_microblaze_0_xlconcat_1/SYSTEM_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_microblaze_0_xlconcat_1 || ORIG_REF_NAME==SYSTEM_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_mdm_1_1/SYSTEM_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_mdm_1_1 || ORIG_REF_NAME==SYSTEM_mdm_1_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_rst_mig_7series_0_83M_1/SYSTEM_rst_mig_7series_0_83M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_rst_mig_7series_0_83M_1 || ORIG_REF_NAME==SYSTEM_rst_mig_7series_0_83M_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_axi_uartlite_0_1/SYSTEM_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_axi_uartlite_0_1 || ORIG_REF_NAME==SYSTEM_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_axi_ethernetlite_0_1/SYSTEM_axi_ethernetlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_axi_ethernetlite_0_1 || ORIG_REF_NAME==SYSTEM_axi_ethernetlite_0_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_axi_timer_0_1/SYSTEM_axi_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_axi_timer_0_1 || ORIG_REF_NAME==SYSTEM_axi_timer_0_1} -quiet] -quiet

# IP: bd/SYSTEM/ip/SYSTEM_axi_smc_1/SYSTEM_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SYSTEM_axi_smc_1 || ORIG_REF_NAME==SYSTEM_axi_smc_1} -quiet] -quiet

# XDC: bd/SYSTEM/SYSTEM_ooc.xdc
