# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Vivado/FINAL/FINAL.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Vivado/FINAL/FINAL.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo c:/Xilinx/Vivado/FINAL/FINAL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/hdl/SYSTEM_wrapper.v
add_files C:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/SYSTEM.bd
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_gpio_0_0/SYSTEM_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_gpio_0_0/SYSTEM_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_gpio_0_0/SYSTEM_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_mig_7series_0_1/SYSTEM_mig_7series_0_1/user_design/constraints/SYSTEM_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_mig_7series_0_1/SYSTEM_mig_7series_0_1/user_design/constraints/SYSTEM_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_mig_7series_0_1/SYSTEM_mig_7series_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_microblaze_0_1/SYSTEM_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_microblaze_0_1/SYSTEM_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_microblaze_0_1/SYSTEM_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_dlmb_v10_1/SYSTEM_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_dlmb_v10_1/SYSTEM_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_ilmb_v10_1/SYSTEM_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_ilmb_v10_1/SYSTEM_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_dlmb_bram_if_cntlr_1/SYSTEM_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_ilmb_bram_if_cntlr_1/SYSTEM_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_lmb_bram_1/SYSTEM_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_xbar_1/SYSTEM_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_microblaze_0_axi_intc_1/SYSTEM_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_microblaze_0_axi_intc_1/SYSTEM_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_microblaze_0_axi_intc_1/SYSTEM_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_mdm_1_1/SYSTEM_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_mdm_1_1/SYSTEM_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_rst_mig_7series_0_83M_1/SYSTEM_rst_mig_7series_0_83M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_rst_mig_7series_0_83M_1/SYSTEM_rst_mig_7series_0_83M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_rst_mig_7series_0_83M_1/SYSTEM_rst_mig_7series_0_83M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_uartlite_0_1/SYSTEM_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_uartlite_0_1/SYSTEM_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_uartlite_0_1/SYSTEM_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_ethernetlite_0_1/SYSTEM_axi_ethernetlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_ethernetlite_0_1/SYSTEM_axi_ethernetlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_ethernetlite_0_1/SYSTEM_axi_ethernetlite_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_ethernetlite_0_1/SYSTEM_axi_ethernetlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_timer_0_1/SYSTEM_axi_timer_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_timer_0_1/SYSTEM_axi_timer_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_1/bd_bb6f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_1/bd_bb6f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_2/bd_bb6f_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_3/bd_bb6f_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_4/bd_bb6f_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_5/bd_bb6f_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_6/bd_bb6f_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_10/bd_bb6f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_11/bd_bb6f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_12/bd_bb6f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_13/bd_bb6f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_14/bd_bb6f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_15/bd_bb6f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_19/bd_bb6f_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_20/bd_bb6f_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_21/bd_bb6f_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_22/bd_bb6f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_23/bd_bb6f_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_24/bd_bb6f_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_25/bd_bb6f_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_26/bd_bb6f_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/bd_0/ip/ip_27/bd_bb6f_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/SYSTEM_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_microblaze_0_1/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Vivado/FINAL/FINAL.srcs/constrs_1/new/arty.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Vivado/FINAL/FINAL.srcs/constrs_1/new/arty.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top SYSTEM_wrapper -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SYSTEM_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SYSTEM_wrapper_utilization_synth.rpt -pb SYSTEM_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
