# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_ilmb_bram_if_cntlr_1/SYSTEM_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'SYSTEM_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_ilmb_bram_if_cntlr_1/SYSTEM_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSTEM_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_ilmb_bram_if_cntlr_1/SYSTEM_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'SYSTEM_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_ilmb_bram_if_cntlr_1/SYSTEM_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSTEM_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
