# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0.xci
# IP: The module: 'SYSTEM_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSTEM_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSTEM_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSTEM_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0.xci
# IP: The module: 'SYSTEM_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSTEM_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSTEM_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/Vivado/FINAL/FINAL.srcs/sources_1/bd/SYSTEM/ip/SYSTEM_clk_wiz_0_0/SYSTEM_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYSTEM_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
